site_name: My Docs

nav:
  - Home: index.md
  - Getting Started: 
    - Features: features/features.md
    - Core Functions: features/functions.md
    - User Interface: features/user-interface.md

theme: readthedocs
